### ISSUE TITLE
complex numbers: coercing literals

### ISSUE THREAD

**Issue by ghost** [OdonataResearchLLC/weyl#3]
Weyl ought to be able to `(coerce #C(0 1) (get-complex-numbers))` to `i`.

**Comment by ghost** [comment]
It looks like it already can.

``` lisp
WEYL> (coerce #c(0 1) (get-complex-numbers))
i
WEYL> 
```

**Comment by ThomasHermann** [comment]
Verified that it does that, closing the issue. Thanks for the feedback.
